spring:
  application:
    name: server

  # Default PostgreSQL Configuration
  # This points to localhost for local development when running `docker-compose up -d postgres`
  # When running inside docker-compose for the full stack, environment variables in docker-compose.yml will override this URL to point to the 'postgres' container.
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
